// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHDFnimblOWFMLTfeO5deHeZPS1xKHz_A',
    appId: '1:541666739411:web:2c984ebcaa1df5aca90026',
    messagingSenderId: '541666739411',
    projectId: 'cal-scheduler-b17bb',
    authDomain: 'cal-scheduler-b17bb.firebaseapp.com',
    storageBucket: 'cal-scheduler-b17bb.appspot.com',
    measurementId: 'G-SQPTDRRKXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWhZDiHRuc33g29kw0RrzY6f0Adv6uTw',
    appId: '1:541666739411:android:1b5a3fb3ce30e6cca90026',
    messagingSenderId: '541666739411',
    projectId: 'cal-scheduler-b17bb',
    storageBucket: 'cal-scheduler-b17bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDhPgWubK35Ik9wLKOlXVldqrUDPZvdo',
    appId: '1:541666739411:ios:67c374575ef4aaada90026',
    messagingSenderId: '541666739411',
    projectId: 'cal-scheduler-b17bb',
    storageBucket: 'cal-scheduler-b17bb.appspot.com',
    iosClientId: '541666739411-ge24lesih7u09hvl22ib2getidc1pdid.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDhPgWubK35Ik9wLKOlXVldqrUDPZvdo',
    appId: '1:541666739411:ios:67c374575ef4aaada90026',
    messagingSenderId: '541666739411',
    projectId: 'cal-scheduler-b17bb',
    storageBucket: 'cal-scheduler-b17bb.appspot.com',
    iosClientId: '541666739411-ge24lesih7u09hvl22ib2getidc1pdid.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );
}
